apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -o kubernetes
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -o kubernetes
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: auth
    spec:
      containers:
      - env:
        - name: COAUTH_NO_SSL
          value: "true"
        - name: RETHINKDB_DB
          value: place_development
        - name: RETHINKDB_HOST
          value: rethink
        - name: TZ
          value: Australia/Sydney
        image: placeos/auth
        imagePullPolicy: ""
        name: auth
        ports:
        - containerPort: 8080
        resources: {}
      hostname: auth
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
