apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -o kubernetes
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: core
  name: core
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: core
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -o kubernetes
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: core
    spec:
      containers:
      - env:
        - name: CORE_HOST
          value: core
        - name: CORE_PORT
          value: "3000"
        - name: ENV
          value: development
        - name: ETCD_HOST
          value: etcd
        - name: REDIS_URL
          value: redis://redis:6379
        - name: RETHINKDB_DB
          value: place_development
        - name: RETHINKDB_HOST
          value: rethink
        - name: SG_ENV
          value: development
        - name: TZ
          value: Australia/Sydney
        image: placeos/core:beta
        imagePullPolicy: ""
        name: core
        ports:
        - containerPort: 3000
        resources: {}
      hostname: core
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
