apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v -o kubernetes
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: core
  name: core
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 3000
  selector:
    io.kompose.service: core
status:
  loadBalancer: {}
