apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -o kubernetes
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: dispatch
  name: dispatch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dispatch
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -o kubernetes
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: dispatch
    spec:
      containers:
      - env:
        - name: SERVER_SECRET
          value: development
        image: placeos/dispatch
        imagePullPolicy: ""
        name: dispatch
        ports:
        - containerPort: 8080
        resources: {}
      hostname: dispatch
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
