apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -o kubernetes
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: elastic
  name: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elastic
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -o kubernetes
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: elastic
    spec:
      containers:
      - env:
        - name: TZ
          value: Australia/Sydney
        - name: bootstrap.memory_lock
          value: "true"
        - name: cluster.routing.allocation.disk.threshold_enabled
          value: "false"
        - name: discovery.type
          value: single-node
        image: blacktop/elasticsearch:7.6
        imagePullPolicy: ""
        name: elastic
        ports:
        - containerPort: 9200
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elastic-claim0
      hostname: elastic
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: elastic-claim0
        persistentVolumeClaim:
          claimName: elastic-claim0
status: {}
