apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v -o kubernetes
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: elastic
  name: elastic
spec:
  ports:
  - name: "8090"
    port: 8090
    targetPort: 9200
  selector:
    io.kompose.service: elastic
status:
  loadBalancer: {}
