apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v -o kubernetes
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: etcd
  name: etcd
spec:
  ports:
  - name: "8091"
    port: 8091
    targetPort: 2379
  - name: "8092"
    port: 8092
    targetPort: 2380
  selector:
    io.kompose.service: etcd
status:
  loadBalancer: {}
