apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -o kubernetes
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: etcd
  name: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: etcd
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -o kubernetes
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: etcd
    spec:
      containers:
      - env:
        - name: ALLOW_NONE_AUTHENTICATION
          value: yes
        - name: TZ
          value: Australia/Sydney
        image: bitnami/etcd:3.3.13
        imagePullPolicy: ""
        name: etcd
        ports:
        - containerPort: 2379
        - containerPort: 2380
        resources: {}
      hostname: etcd
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
