apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -o kubernetes
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -o kubernetes
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - env:
        - name: TZ
          value: Australia/Sydney
        image: yobasystems/alpine-nginx
        imagePullPolicy: ""
        name: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-claim0
          readOnly: true
        - mountPath: /etc/nginx/html/
          name: nginx-claim1
          readOnly: true
        - mountPath: /etc/nginx/ssl/
          name: nginx-claim2
          readOnly: true
      hostname: nginx
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: nginx-claim0
        persistentVolumeClaim:
          claimName: nginx-claim0
          readOnly: true
      - name: nginx-claim1
        persistentVolumeClaim:
          claimName: nginx-claim1
          readOnly: true
      - name: nginx-claim2
        persistentVolumeClaim:
          claimName: nginx-claim2
          readOnly: true
status: {}
