apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -o kubernetes
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: play
  name: play
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: play
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -o kubernetes
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: play
    spec:
      containers:
      - command:
        - crystal
        - play
        - -b
        - 0.0.0.0
        - -p
        - "4040"
        env:
        - name: CORE_URL
          value: http://core:3000
        - name: ENV
          value: development
        - name: ES_HOST
          value: elastic
        - name: ETCD_HOST
          value: etcd
        - name: REDIS_URL
          value: redis://redis:6379
        - name: RETHINKDB_DB
          value: place_development
        - name: RETHINKDB_HOST
          value: rethink
        - name: SG_ENV
          value: development
        - name: TZ
          value: Australia/Sydney
        image: placeos/play
        imagePullPolicy: ""
        name: play
        ports:
        - containerPort: 4040
        - containerPort: 4041
        - containerPort: 4042
        - containerPort: 4043
        - containerPort: 4044
        - containerPort: 4045
        - containerPort: 4046
        - containerPort: 4047
        - containerPort: 4048
        - containerPort: 4049
        - containerPort: 4050
        - containerPort: 4051
        - containerPort: 4052
        - containerPort: 4053
        - containerPort: 4054
        - containerPort: 4055
        - containerPort: 4056
        - containerPort: 4057
        - containerPort: 4058
        - containerPort: 4059
        - containerPort: 4060
        - containerPort: 22
        resources: {}
        volumeMounts:
        - mountPath: /placeos/drivers
          name: play-claim0
        workingDir: /placeos/core
      hostname: play
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: play-claim0
        persistentVolumeClaim:
          claimName: play-claim0
status: {}
