apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v -o kubernetes
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: play
  name: play
spec:
  ports:
  - name: "4040"
    port: 4040
    targetPort: 4040
  - name: "4041"
    port: 4041
    targetPort: 4041
  - name: "4042"
    port: 4042
    targetPort: 4042
  - name: "4043"
    port: 4043
    targetPort: 4043
  - name: "4044"
    port: 4044
    targetPort: 4044
  - name: "4045"
    port: 4045
    targetPort: 4045
  - name: "4046"
    port: 4046
    targetPort: 4046
  - name: "4047"
    port: 4047
    targetPort: 4047
  - name: "4048"
    port: 4048
    targetPort: 4048
  - name: "4049"
    port: 4049
    targetPort: 4049
  - name: "4050"
    port: 4050
    targetPort: 4050
  - name: "4051"
    port: 4051
    targetPort: 4051
  - name: "4052"
    port: 4052
    targetPort: 4052
  - name: "4053"
    port: 4053
    targetPort: 4053
  - name: "4054"
    port: 4054
    targetPort: 4054
  - name: "4055"
    port: 4055
    targetPort: 4055
  - name: "4056"
    port: 4056
    targetPort: 4056
  - name: "4057"
    port: 4057
    targetPort: 4057
  - name: "4058"
    port: 4058
    targetPort: 4058
  - name: "4059"
    port: 4059
    targetPort: 4059
  - name: "4060"
    port: 4060
    targetPort: 4060
  - name: "4022"
    port: 4022
    targetPort: 22
  selector:
    io.kompose.service: play
status:
  loadBalancer: {}
