apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -o kubernetes
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -o kubernetes
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - env:
        - name: TZ
          value: Australia/Sydney
        image: eqalpha/keydb
        imagePullPolicy: ""
        name: redis
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: redis-claim0
        - mountPath: /usr/local/etc/redis/redis.conf
          name: redis-claim1
      hostname: redis
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: redis-claim0
        persistentVolumeClaim:
          claimName: redis-claim0
      - name: redis-claim1
        persistentVolumeClaim:
          claimName: redis-claim1
status: {}
