apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -o kubernetes
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: rethink
  name: rethink
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rethink
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -o kubernetes
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: rethink
    spec:
      containers:
      - env:
        - name: TZ
          value: Australia/Sydney
        image: rethinkdb:2.4
        imagePullPolicy: ""
        name: rethink
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /data/rethinkdb_data/
          name: rethink-claim0
      hostname: rethink
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: rethink-claim0
        persistentVolumeClaim:
          claimName: rethink-claim0
status: {}
