apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v -o kubernetes
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: rethink
  name: rethink
spec:
  ports:
  - name: "8093"
    port: 8093
    targetPort: 8080
  selector:
    io.kompose.service: rethink
status:
  loadBalancer: {}
