apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v -o kubernetes
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: rubber-soul
  name: rubber-soul
spec:
  ports:
  - name: "8084"
    port: 8084
    targetPort: 3000
  selector:
    io.kompose.service: rubber-soul
status:
  loadBalancer: {}
