apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -o kubernetes
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: rubber-soul
  name: rubber-soul
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rubber-soul
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -o kubernetes
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: rubber-soul
    spec:
      containers:
      - env:
        - name: ES_HOST
          value: elastic
        - name: RETHINKDB_DB
          value: place_development
        - name: RETHINKDB_HOST
          value: rethink
        - name: TZ
          value: Australia/Sydney
        image: placeos/rubber-soul:v1.5.3
        imagePullPolicy: ""
        name: rubber-soul
        ports:
        - containerPort: 3000
        resources: {}
      hostname: rubber-soul
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
