apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -o kubernetes
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: triggers
  name: triggers
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: triggers
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -o kubernetes
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: triggers
    spec:
      containers:
      - env:
        - name: ENV
          value: development
        - name: REDIS_URL
          value: redis://redis:6379
        - name: RETHINKDB_DB
          value: place_development
        - name: RETHINKDB_HOST
          value: rethink
        - name: SG_ENV
          value: development
        - name: TZ
          value: Australia/Sydney
        image: placeos/triggers
        imagePullPolicy: ""
        name: triggers
        resources: {}
      hostname: triggers
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
